name: custom_lint_example_plugin
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  riverpod: ^2.0.0
  web: ^0.5.1

dev_dependencies:
  custom_lint:
  custom_lint_example_lint:
    path: ../example/example_lint
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ExamplePlugin
      web:
        pluginClass: ExamplePluginWeb
        fileName: example_plugin_web.dart
