name: custom_lint_example_plugin
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint:
  custom_lint_example_plugin_example_lint:
    path: ./example_lint

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ExamplePlugin
      web:
        pluginClass: ExamplePluginWeb
        fileName: example_plugin_web.dart
